<?php

namespace ContainerA7eaUKh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomerPreferencesControllerService extends AdminKernelProdContainer
{
    /*
     * Gets the public 'PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerPreferencesController' shared autowired service.
     *
     * @return \PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerPreferencesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['PrestaShopBundle\\Controller\\Admin\\Configure\\ShopParameters\\CustomerPreferencesController'] = $instance = new \PrestaShopBundle\Controller\Admin\Configure\ShopParameters\CustomerPreferencesController();

        $instance->setContainer(($container->privates['.service_locator.Xnms9qc'] ?? $container->load('get_ServiceLocator_Xnms9qcService'))->withContext('PrestaShopBundle\\Controller\\Admin\\Configure\\ShopParameters\\CustomerPreferencesController', $container));

        return $instance;
    }
}
