---
deployment:
  tasks:
    - /bin/cp -rf /home1/harmakko/repositories/harmaalwale.com/. /home1/harmakko/public_html/
    - /bin/rm -rf /home1/harmakko/public_html/.git
    - /bin/rm -rf /home1/harmakko/public_html/.github
    - /bin/rm -f /home1/harmakko/public_html/.cpanel.yml
    - /bin/rm -f /home1/harmakko/public_html/README.md
    - /bin/rm -f /home1/harmakko/public_html/deploy.bat
    - /bin/chmod 644 /home1/harmakko/public_html/.htaccess
    - /usr/bin/find /home1/harmakko/public_html/api -name "*.php" -exec chmod 644 {} \;
    - /bin/echo "Deployed at $(date)"
