---
deployment:
  tasks:
    # Set deploy path
    - export DEPLOYPATH=/home1/harmakko/public_html

    # Sync all files to public_html (preserves existing files not in repo)
    - rsync -av --exclude='.git' --exclude='.github' --exclude='.cpanel.yml' --exclude='README.md' --exclude='deploy.bat' . $DEPLOYPATH/

    # Set correct permissions
    - find $DEPLOYPATH/api -name "*.php" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.html" -exec chmod 644 {} \;
    - find $DEPLOYPATH -name "*.js" -exec chmod 644 {} \;
    - chmod 644 $DEPLOYPATH/.htaccess

    # Confirm
    - echo "✅ HarmaalWale deployed successfully at $(date)"
    - echo "📁 Files in public_html:"
    - ls $DEPLOYPATH
