<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA7eaUKh\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA7eaUKh/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerA7eaUKh.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerA7eaUKh\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerA7eaUKh\AdminKernelProdContainer([
    'container.build_hash' => 'A7eaUKh',
    'container.build_id' => '0146220a',
    'container.build_time' => 1756020967,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA7eaUKh');
